name: style-fixer | static-analysis 
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  static-analysis-and-style-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up PHP 8.3
      run: |
        sudo apt-get update
        sudo add-apt-repository ppa:ondrej/php -y
        sudo apt-get update
        sudo apt-get install -y php8.3 php8.3-cli
    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
    - name: Install dependencies
      run: composer install --no-progress
    - name: Run PHP-CS-Fixer
      run: vendor/bin/php-cs-fixer check src -vv 
    - name: Run PHPStan
      run: vendor/bin/phpstan analyse